stages:
  - build
  - analysis

variables:
  DEBIAN_FRONTEND: noninteractive

build-ubuntu:
  image: ubuntu:devel
  stage: build
  except:
    - tags
  before_script:
    - apt-get update
    - apt-get install -q -y --no-install-recommends
                      adwaita-icon-theme
                      autoconf-archive
                      automake
                      autopoint
                      build-essential
                      docbook-to-man
                      docbook-xsl
                      gettext
                      gnome-settings-daemon-dev
                      intltool
                      libcpufreq-dev
                      libglib2.0-dev
                      libgnome-panel-dev
                      libgtk-3-dev
                      libgtop2-dev
                      libgucharmap-2-90-dev
                      libgweather-3-dev
                      libnotify-dev
                      libpanel-applet-dev
                      libpolkit-gobject-1-dev
                      libtracker-sparql-2.0-dev
                      libtool
                      libupower-glib-dev
                      libwnck-3-dev
                      libx11-dev
                      libxml2-dev
                      x11proto-dev
                      yelp-tools
  script:
    - ./autogen.sh --disable-Werror
    - make
    - make distcheck

coverity:
  image: ubuntu:devel
  stage: analysis
  when: manual
  before_script:
    - apt-get update
    - apt-get install -q -y --no-install-recommends
                      adwaita-icon-theme
                      autoconf-archive
                      automake
                      autopoint
                      build-essential
                      ca-certificates
                      clang
                      curl
                      docbook-to-man
                      docbook-xsl
                      gettext
                      gnome-settings-daemon-dev
                      intltool
                      libcpufreq-dev
                      libglib2.0-dev
                      libgnome-panel-dev
                      libgtk-3-dev
                      libgtop2-dev
                      libgucharmap-2-90-dev
                      libgweather-3-dev
                      libnotify-dev
                      libpanel-applet-dev
                      libpolkit-gobject-1-dev
                      libtracker-sparql-2.0-dev
                      libtool
                      libupower-glib-dev
                      libwnck-3-dev
                      libx11-dev
                      libxml2-dev
                      x11proto-dev
                      yelp-tools
  script:
    - curl https://scan.coverity.com/download/linux64
      --data "token=$COVERITY_TOKEN&project=gnome-applets"
      --output /tmp/coverity_tool.tgz
    - tar zxf /tmp/coverity_tool.tgz
    - CC=clang ./autogen.sh --disable-Werror
    - ./cov-analysis-linux64-*/bin/cov-build --dir cov-int make
    - tar czf cov-int.tar.gz cov-int
    - curl --form token=$COVERITY_TOKEN
      --form email=alberts.muktupavels@gmail.com
      --form file=@cov-int.tar.gz
      --form version="$(autoconf --trace='AC_INIT:$2')-$CI_COMMIT_SHORT_SHA"
      https://scan.coverity.com/builds?project=gnome-applets
  only:
    - master
