stages:
  - build

build-ubuntu:
  image: ubuntu:devel
  stage: build
  before_script:
    - apt-get update
    - apt-get install -q -y --no-install-recommends
                      adwaita-icon-theme
                      autoconf-archive
                      automake
                      autopoint
                      build-essential
                      docbook-to-man
                      docbook-xsl
                      gettext
                      gnome-settings-daemon-dev
                      intltool
                      libcpufreq-dev
                      libdbus-1-dev
                      libdbus-glib-1-dev
                      libglib2.0-dev
                      libgtk-3-dev
                      libgtop2-dev
                      libgucharmap-2-90-dev
                      libgweather-3-dev
                      libnotify-dev
                      libpanel-applet-dev
                      libpolkit-gobject-1-dev
                      libtracker-sparql-2.0-dev
                      libtool
                      libupower-glib-dev
                      libwnck-3-dev
                      libx11-dev
                      libxml2-dev
                      xsltproc
                      yelp-tools
  script:
    - ./autogen.sh --disable-Werror
    - make
    - make distcheck
