/* Automatically generated by po2tbl.sed from battstat_applet.pot.  */

#if HAVE_CONFIG_H
# include <config.h>
#endif

#include "libgettext.h"

const struct _msg_ent _msg_tbl[] = {
  {"", 1},
  {"High", 2},
  {"Low", 3},
  {"Critical", 4},
  {"Charging", 5},
  {"\
System is running on %s power\n\
Battery: %d%% (%s)", 6},
  {"AC", 7},
  {"battery", 8},
  {"System is running on %s power", 9},
  {"Battery low (%d%%) and AC is %s", 10},
  {"online", 11},
  {"offline", 12},
  {"System is running on %s power. Battery: %d%% (%s)", 13},
  {"System is running on %s power. Battery: Not present", 14},
  {"Battery: %d%% (%s)", 15},
  {"Battery: Not present", 16},
  {"Battery is now fully re-charged!", 17},
  {"\
Can't open the APM device!\n\
\n\
Make sure you have read permission to the\n\
APM device.", 18},
  {"\
The APM Management subsystem seems to be disabled.\n\
Try executing \"apm -e 1\" (FreeBSD) and see if \n\
that helps.\n", 19},
  {"Battery status utility", 20},
  {" (C) 2000 The Gnulix Society", 21},
  {"This utility show the status of your laptop battery.", 22},
  {"You can't hide all elements of the applet!", 23},
  {"System is running on %s power.", 24},
  {"Battstat Settings", 25},
  {"General", 26},
  {"Battery color levels (%)", 27},
  {"Yellow:", 28},
  {"Orange:", 29},
  {"Red:", 30},
  {"Preview", 31},
  {"Warnings", 32},
  {"Notify me when battery charge is low", 33},
  {"Notify me when battery is fully re-charged", 34},
  {"Beep when either of the above is true", 35},
  {"Percentage text:", 36},
  {"Suspend command:", 37},
  {"Appearance", 38},
  {"Progress bar direction", 39},
  {"Move towards top", 40},
  {"Move towards bottom", 41},
  {"Orientation", 42},
  {"Horizontal", 43},
  {"Square", 44},
  {"Applet layout", 45},
  {"Show", 46},
  {"Hide", 47},
  {"Status dock", 48},
  {"Use the status dock", 49},
  {"Can't create applet!\n", 50},
  {"Properties...", 51},
  {"About...", 52},
  {"Help", 53},
  {"Suspend laptop", 54},
};

int _msg_tbl_length = 54;
