/* Automatically generated by po2tbl.sed from battstat_applet.pot.  */

#if HAVE_CONFIG_H
# include <config.h>
#endif

#include "libgettext.h"

const struct _msg_ent _msg_tbl[] = {
  {"", 1},
  {"High", 2},
  {"Low", 3},
  {"Critical", 4},
  {"Charging", 5},
  {"\
System is running on %s power\n\
Battery: %d%% (%s)", 6},
  {"AC", 7},
  {"battery", 8},
  {"System is running on %s power", 9},
  {"Battery low (%d%%) and AC is %s", 10},
  {"online", 11},
  {"offline", 12},
  {"System is running on %s power. Battery: %d%% (%s)", 13},
  {"System is running on %s power. Battery: Not present", 14},
  {"Battery: %d%% (%s)", 15},
  {"Battery: Not present", 16},
  {"Battery is now fully re-charged!", 17},
  {"\
Can't open the APM device!\n\
\n\
Make sure you have read permission to the\n\
APM device.", 18},
  {"\
The APM Management subsystem seems to be disabled.\n\
Try executing \"apm -e 1\" (FreeBSD) and see if \n\
that helps.\n", 19},
  {"Battery status utility", 20},
  {" (C) 2000 The Gnulix Society", 21},
  {"This utility show the status of your laptop battery.", 22},
  {"You can't hide all elements of the applet!", 23},
  {"System is running on %s power.", 24},
  {"Can't create applet!\n", 25},
  {"Properties...", 26},
  {"About...", 27},
  {"Help", 28},
  {"Suspend laptop", 29},
  {"Battstat Settings", 30},
  {"General", 31},
  {"Battery color levels (%)", 32},
  {"Yellow:", 33},
  {"Orange:", 34},
  {"Red:", 35},
  {"Preview", 36},
  {"Warnings", 37},
  {"Notify me when battery charge is low", 38},
  {"Notify me when battery is fully re-charged", 39},
  {"Beep when either of the above is true", 40},
  {"Use my own font instead of the default GNOME font", 41},
  {"Percentage text:", 42},
  {"Suspend command:", 43},
  {"Appearance", 44},
  {"Progress bar direction", 45},
  {"Move towards top", 46},
  {"Move towards bottom", 47},
  {"Orientation", 48},
  {"Horizontal", 49},
  {"Square", 50},
  {"Applet layout", 51},
  {"Show", 52},
  {"Hide", 53},
  {"Status dock", 54},
  {"Use the status dock", 55},
};

int _msg_tbl_length = 55;
