#!/usr/bin/env python

import sys, invest.chart, gtk

# Prepare i18n
import gettext, locale
gettext.bindtextdomain(invest.defs.GETTEXT_PACKAGE, invest.defs.GNOMELOCALEDIR)
gettext.textdomain(invest.defs.GETTEXT_PACKAGE)
locale.bindtextdomain(invest.defs.GETTEXT_PACKAGE, invest.defs.GNOMELOCALEDIR)
locale.textdomain(invest.defs.GETTEXT_PACKAGE)

if __name__ == "__main__":
	win = invest.chart.show_chart(sys.argv[1:])
	win.connect("destroy", lambda x: gtk.main_quit())
	gtk.main()
